-- Create the PROPOSAL table
CREATE TABLE public."PROPOSAL" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "PROPOSAL DATA" text null,
  "STATUS" text null,
  constraint PROPOSAL_pkey primary key (id)
);

-- Enable RLS but allow public read access for proposals (shareable links)
ALTER TABLE public."PROPOSAL" ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read proposals (they are shareable via links)
CREATE POLICY "Proposals are publicly viewable" 
ON public."PROPOSAL" 
FOR SELECT 
USING (true);